markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
safe: false
lsi: false

title: jasonrhodes.github.com
twitter: rhodesjason